import type { Metadata } from "next";
import "./globals.css";
import Header from "@/_Components/Header"; // ヘッダーコンポーネントをインポート

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* bodyに基本的なスタイルを適用 */}
      <body style={{ backgroundColor: 'white', color: 'black', margin: 0 }}>
        <Header />
        <main style={{ padding: '2rem' }}>
          {children}
        </main>
      </body>
    </html>
  );
}